### ISSUE TITLE
KerasModeltoJSON.py execution

### ISSUE THREAD

**Issue by ebteles** [adamtiger/NNSharp#1]
Error:

  File "KerasModeltoJSON.py", line 20, in __model_to_JSON
    conf = model.get_config()

AttributeError: 'str' object has no attribute 'get_config'

**Comment by adamtiger** [comment]
Thank you for the comment!

It is strange that your model is an 'str' object instead of a 'Sequential' one. Firstly, I would recommend to check out the KerasTestGenerator.py in the folder PythonUtils to see examples how I have used KerasModeltoJSON during my tests. In my opinion you substituted the string representation of the model in the first argument.

If the problem still persists, then let me know and send me some further details how I can reproduce the error.
